# Generated by Django 4.0 on 2021-12-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ageneral_customerform_decent_elegant_elegant_jr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrical_appliances',
            old_name='appliances_img1',
            new_name='appliances_img',
        ),
        migrations.RenameField(
            model_name='industrial_coolers',
            old_name='coolers_img1',
            new_name='coolers_img',
        ),
        migrations.RenameField(
            model_name='pvc_pipes',
            old_name='pvc_img1',
            new_name='pvc_img',
        ),
        migrations.RenameField(
            model_name='residential_coolers',
            old_name='coolers_img1',
            new_name='coolers_img',
        ),
        migrations.RenameField(
            model_name='ro_spare_parts',
            old_name='ro_img1',
            new_name='ro_img',
        ),
    ]
