# Generated by Django 4.0 on 2021-12-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_appliances_img1_electrical_appliances_appliances_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chakki',
            old_name='Chakki_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='industrial_coolers',
            old_name='coolers_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='pvc_pipes',
            old_name='pvc_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='residential_coolers',
            old_name='coolers_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='ro_spare_parts',
            old_name='ro_img',
            new_name='img',
        ),
    ]
