# Generated by Django 4.0 on 2021-12-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_category_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrical_appliances',
            old_name='appliances_img',
            new_name='img',
        ),
    ]
