# Generated by Django 4.0 on 2021-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_chakki_id_alter_electrical_appliances_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chakki',
            old_name='img',
            new_name='Chakki_img',
        ),
        migrations.RenameField(
            model_name='electrical_appliances',
            old_name='img',
            new_name='appliances_img',
        ),
        migrations.RenameField(
            model_name='industrial_coolers',
            old_name='img',
            new_name='coolers_img',
        ),
        migrations.RenameField(
            model_name='pvc_pipes',
            old_name='img',
            new_name='pvc_img',
        ),
        migrations.RenameField(
            model_name='residential_coolers',
            old_name='img',
            new_name='coolers_img',
        ),
        migrations.RenameField(
            model_name='ro_spare_parts',
            old_name='img',
            new_name='ro_img',
        ),
        migrations.AlterField(
            model_name='industrial_coolers',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='residential_coolers',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
