# Generated by Django 4.0 on 2021-12-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_magic_cook_magic_plus_magic_vc_max_plus_olive_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='magic_cook',
        ),
        migrations.DeleteModel(
            name='magic_plus',
        ),
        migrations.DeleteModel(
            name='max_plus',
        ),
        migrations.DeleteModel(
            name='olive',
        ),
        migrations.DeleteModel(
            name='olive_plus',
        ),
        migrations.DeleteModel(
            name='olive_plus_SS',
        ),
        migrations.DeleteModel(
            name='super_star',
        ),
        migrations.DeleteModel(
            name='super_star_plus',
        ),
    ]
