# Generated by Django 4.0 on 2021-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_magic_cook_magic_plus_magic_vc_max_plus_olive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='smart_2hp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/chakki/detailpage/')),
                ('capacity', models.CharField(max_length=500)),
                ('p1', models.CharField(max_length=300)),
                ('p2', models.CharField(max_length=300)),
                ('p3', models.CharField(max_length=300)),
                ('p4', models.CharField(max_length=300)),
                ('p5', models.CharField(max_length=300)),
                ('p6', models.CharField(max_length=300)),
                ('p7', models.CharField(max_length=300)),
                ('gurantee', models.CharField(max_length=300)),
                ('design', models.CharField(max_length=300)),
            ],
        ),
    ]
