# Generated by Django 4.0 on 2021-12-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_smart_2hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='olivepremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/chakki/detailpage/')),
                ('capacity', models.CharField(max_length=500)),
                ('p1', models.CharField(max_length=300)),
                ('p2', models.CharField(max_length=300)),
                ('p3', models.CharField(max_length=300)),
                ('p4', models.CharField(max_length=300)),
                ('p5', models.CharField(max_length=300)),
                ('p6', models.CharField(max_length=300)),
                ('p7', models.CharField(max_length=300)),
                ('p8', models.CharField(max_length=300)),
                ('gurantee', models.CharField(max_length=300)),
                ('design', models.CharField(max_length=300)),
                ('p9', models.CharField(max_length=300)),
                ('p10', models.CharField(max_length=300)),
                ('p11', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='olivepro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/chakki/detailpage/')),
                ('capacity', models.CharField(max_length=500)),
                ('p1', models.CharField(max_length=300)),
                ('p2', models.CharField(max_length=300)),
                ('p3', models.CharField(max_length=300)),
                ('p4', models.CharField(max_length=300)),
                ('p5', models.CharField(max_length=300)),
                ('p6', models.CharField(max_length=300)),
                ('p7', models.CharField(max_length=300)),
                ('p8', models.CharField(max_length=300)),
                ('gurantee', models.CharField(max_length=300)),
                ('design', models.CharField(max_length=300)),
                ('p9', models.CharField(max_length=300)),
                ('p10', models.CharField(max_length=300)),
                ('p11', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
