# Generated by Django 4.0 on 2021-12-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_olivepremium_olivepro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='olivepremium',
        ),
        migrations.DeleteModel(
            name='olivepro',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='design',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='gurantee',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='img',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='name',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='olive',
            name='p6',
        ),
    ]
