# Generated by Django 4.0 on 2021-12-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_olivepremium_delete_olivepro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olive',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
