# Generated by Django 4.0 on 2021-12-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_olive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='olive',
            name='capacity',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='olive',
            name='design',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='gurantee',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='img',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive',
            name='p1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='p2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='p3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='p4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='p5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='olive',
            name='p6',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='olive',
            name='p7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='olive',
            name='p8',
            field=models.CharField(default='', max_length=300),
        ),
    ]
