# Generated by Django 4.0 on 2021-12-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_olive_capacity_olive_design_olive_gurantee_olive_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic_cook',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='magic_plus',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='magic_plus',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus_ss',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star_plus',
            name='img2',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star_plus',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star_plus',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star_plus',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
    ]
