# Generated by Django 4.0 on 2021-12-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_magic_cook_img2_magic_plus_img2_magic_plus_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic_cook',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='magic_cook',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='magic_cook',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='max_plus',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='max_plus',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='max_plus',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus_ss',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus_ss',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='olive_plus_ss',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star',
            name='img3',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star',
            name='img4',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
        migrations.AddField(
            model_name='super_star',
            name='img5',
            field=models.ImageField(default='', upload_to='images/product_image/chakki/detailpage/'),
        ),
    ]
