# Generated by Django 4.0 on 2021-12-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_max_plus_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_electric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('img2', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('colour', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('p1', models.CharField(max_length=300)),
                ('p2', models.CharField(max_length=300)),
                ('p3', models.CharField(max_length=300)),
                ('p4', models.CharField(max_length=300)),
                ('p5', models.CharField(max_length=300)),
                ('gurantee', models.CharField(max_length=300)),
                ('design', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ceiling_fan1',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='ceiling_fan2',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='ceiling_fan3',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='gasGeyser1',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='gasGeyser2',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='heater1',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='heater2',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='heater3',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='heater4',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='iron1',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='iron2',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='iron3',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='iron4',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='kettle1',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='kettle2',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='kettle3',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='pedestal_fan1',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='pedestal_fan2',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
        migrations.CreateModel(
            name='water_rod',
            fields=[
                ('base_electric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.base_electric')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('home.base_electric',),
        ),
    ]
