# Generated by Django 4.0 on 2021-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_base_electric_ceiling_fan1_ceiling_fan2_ceiling_fan3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ceiling_fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gasgeyser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
                ('p5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='heater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='iron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kettle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pedestal_fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ceiling_fan1',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='ceiling_fan2',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='ceiling_fan3',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='gasgeyser1',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='gasgeyser2',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='heater1',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='heater2',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='heater3',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='heater4',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='iron1',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='iron2',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='iron3',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='iron4',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='kettle1',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='kettle2',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='kettle3',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='pedestal_fan1',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='pedestal_fan2',
            name='base_electric_ptr',
        ),
        migrations.RemoveField(
            model_name='water_rod',
            name='base_electric_ptr',
        ),
        migrations.DeleteModel(
            name='base_electric',
        ),
        migrations.DeleteModel(
            name='ceiling_fan1',
        ),
        migrations.DeleteModel(
            name='ceiling_fan2',
        ),
        migrations.DeleteModel(
            name='ceiling_fan3',
        ),
        migrations.DeleteModel(
            name='gasGeyser1',
        ),
        migrations.DeleteModel(
            name='gasGeyser2',
        ),
        migrations.DeleteModel(
            name='heater1',
        ),
        migrations.DeleteModel(
            name='heater2',
        ),
        migrations.DeleteModel(
            name='heater3',
        ),
        migrations.DeleteModel(
            name='heater4',
        ),
        migrations.DeleteModel(
            name='iron1',
        ),
        migrations.DeleteModel(
            name='iron2',
        ),
        migrations.DeleteModel(
            name='iron3',
        ),
        migrations.DeleteModel(
            name='iron4',
        ),
        migrations.DeleteModel(
            name='kettle1',
        ),
        migrations.DeleteModel(
            name='kettle2',
        ),
        migrations.DeleteModel(
            name='kettle3',
        ),
        migrations.DeleteModel(
            name='pedestal_fan1',
        ),
        migrations.DeleteModel(
            name='pedestal_fan2',
        ),
        migrations.DeleteModel(
            name='water_rod',
        ),
    ]
