# Generated by Django 4.0 on 2021-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_ceiling_fan_gasgeyser_heater_iron_kettle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='customer_problem',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
