# Generated by Django 4.0 on 2022-01-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_customerform_customer_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='grinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/chakki/')),
                ('name', models.CharField(max_length=40)),
                ('capacity', models.CharField(max_length=20)),
                ('inherit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chakki')),
            ],
        ),
    ]
