# Generated by Django 4.0 on 2022-01-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_grinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grinding',
            name='inherit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
