# Generated by Django 4.0 on 2022-01-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_grinding_inherit'),
    ]

    operations = [
        migrations.CreateModel(
            name='blender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chimney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hand_juicer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='induction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='madhani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mixer_grinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='motor_pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='water_heater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/product_image/electric/detailpage/')),
                ('gurantee', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=100)),
                ('p2', models.CharField(max_length=100)),
                ('p3', models.CharField(max_length=100)),
                ('p4', models.CharField(max_length=100)),
            ],
        ),
    ]
