# Generated by Django 4.0 on 2022-01-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_blender_chimney_chopper_hand_juicer_induction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrical_appliances',
            old_name='category3',
            new_name='category4',
        ),
        migrations.RenameField(
            model_name='industrial_coolers',
            old_name='category2_2',
            new_name='category3',
        ),
        migrations.RenameField(
            model_name='pvc_pipes',
            old_name='category5',
            new_name='category6',
        ),
        migrations.RenameField(
            model_name='residential_coolers',
            old_name='category2_1',
            new_name='category2',
        ),
        migrations.RenameField(
            model_name='ro_spare_parts',
            old_name='category4',
            new_name='category5',
        ),
        migrations.CreateModel(
            name='Tubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size1', models.CharField(max_length=100)),
                ('capacity1', models.CharField(max_length=100)),
                ('size2', models.CharField(max_length=100)),
                ('capacity2', models.CharField(max_length=100)),
                ('size3', models.CharField(max_length=100)),
                ('capacity3', models.CharField(max_length=100)),
                ('size4', models.CharField(max_length=100)),
                ('capacity4', models.CharField(max_length=100)),
                ('size5', models.CharField(max_length=100)),
                ('capacity5', models.CharField(max_length=100)),
                ('tubs_img', models.ImageField(upload_to='images/tubs/')),
                ('category7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
